### ISSUE TITLE
Rebuild including new method parameters

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-hubspot-source#9]
Support
**Requirements**
Use `offset` and `count` parameters to support pagination
Build methods for each of the following existing hubspot endpoints
- [`getAllCompanies`](http://developers.hubspot.com/docs/methods/companies/get-all-companies)
- [`getAllContacts`](http://developers.hubspot.com/docs/methods/contacts/get_contacts)
- [`getContactLists`](http://developers.hubspot.com/docs/methods/lists/get_lists)
- [`getAllDeals`](http://developers.hubspot.com/docs/methods/deals/get-all-deals)
- [`getAllDealPipelines`](http://developers.hubspot.com/docs/methods/deal-pipelines/get-all-deal-pipelines)
- [`getCampaigns`](http://developers.hubspot.com/docs/methods/email/get_campaigns_by_id)
- [`getEmailEvents`](http://developers.hubspot.com/docs/methods/email/get_events)
     - Will require `getCampaigns` to get an array of `campaign_ids`
- [`getAllEngagements`](http://developers.hubspot.com/docs/methods/engagements/get-all-engagements)
- [`getKeywords`](http://developers.hubspot.com/docs/methods/keywords/get_keywords)
- [`getPublishingChannels`](http://developers.hubspot.com/docs/methods/social_media/get_channels)

**Comment by macmccann** [comment]
Can I start working on this?

**Comment by benjamingregory** [comment]
@dansweet1 @bonominijl @perryao 

I'll defer to you on priority of this for Mac's time.

**Comment by ryw** [comment]
no more work on aries
